#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/ollama
ollama_model: 'gemma4:e4b'

ollama_host: '0.0.0.0:11434'

ollama_models_dir: '/var/lib/ollama'

ollama_allowed_network: '192.168.1.0/24'
