---
- name: Ensure k3s group exists
  ansible.builtin.group:
      name: k3s
      state: present

- name: Add k3s user to k3s group
  ansible.builtin.user:
      name: '{{ k3s_user }}'
      groups: k3s
      append: true

- name: Configure k3s
  ansible.builtin.template:
      src: config.yaml.j2
      dest: /etc/rancher/k3s/config.yaml
      owner: root
      group: root
      mode: '0644'
  notify: Restart k3s

- name: Ensure k3s service is enabled and running
  ansible.builtin.systemd:
      name: '{{ k3s_service_name }}'
      enabled: true
      state: started

- name: Wait for k3s kubeconfig
  ansible.builtin.wait_for:
      path: '{{ k3s_kubeconfig }}'
      timeout: 60

- name: Set kubeconfig group ownership
  ansible.builtin.file:
      path: '{{ k3s_kubeconfig }}'
      owner: root
      group: k3s
      mode: '0640'

- name: Verify k3s node
  ansible.builtin.command:
      cmd: kubectl get nodes
  become: true
  environment:
      KUBECONFIG: '{{ k3s_kubeconfig }}'
  register: k3s_nodes
  changed_when: false

- name: Show k3s nodes
  ansible.builtin.debug:
      var: k3s_nodes.stdout_lines

- name: Configure Traefik HTTP to HTTPS redirect
  become: true
  ansible.builtin.template:
      src: traefik-config.yaml.j2
      dest: /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
      mode: '0644'
