---
- name: Check whether k3s is installed
  ansible.builtin.stat:
      path: /usr/local/bin/k3s
  register: k3s_binary

- name: Download k3s installer
  ansible.builtin.get_url:
      url: '{{ k3s_install_script_url }}'
      dest: /tmp/install-k3s.sh
      mode: '0755'
  when: not k3s_binary.stat.exists

- name: Install k3s
  ansible.builtin.command:
      cmd: /tmp/install-k3s.sh
  environment:
      INSTALL_K3S_VERSION: '{{ k3s_version }}'
  when:
      - not k3s_binary.stat.exists
      - k3s_version | length > 0

- name: Install latest k3s
  ansible.builtin.command:
      cmd: /tmp/install-k3s.sh
  when:
      - not k3s_binary.stat.exists
      - k3s_version | length == 0

- name: Enable and start k3s
  ansible.builtin.systemd:
      name: '{{ k3s_service_name }}'
      enabled: true
      state: started
