---
- name: Configure Think Server
  hosts: think-server
  become: true

  roles:
      - docker
      - k3s
      - helm
      - tailscale
      - cloudflared
      - ufw
      - argocd
      - github_runner

      - samba
      - jellyfin
      - immich
      - portainer
      - homarr
