---
- name: Configure Think Server
  hosts: think-server
  become: true

  roles:
      - docker
      - k3s
      - tailscale
      - argocd
      - cloudflared

      - samba
      - jellyfin
      - immich
      - portainer
      - homarr
