---
- name: Create Immich directory
  ansible.builtin.file:
      path: '{{ immich_compose_dir }}'
      state: directory
      owner: root
      group: root
      mode: '0755'

- name: Create Immich database directory
  ansible.builtin.file:
      path: '{{ immich_db_location }}'
      state: directory
      owner: root
      group: root
      mode: '0755'

- name: Create Immich upload directory
  ansible.builtin.file:
      path: '{{ immich_upload_location }}'
      state: directory
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      mode: '0775'
