---
- name: Install Docker packages
  ansible.builtin.apt:
      name: '{{ docker_packages }}'
      state: present
      update_cache: true

- name: Enable Docker service
  ansible.builtin.systemd:
      name: docker
      enabled: '{{ docker_service_enabled }}'
      state: "{{ 'started' if docker_service_started else 'stopped' }}"

- name: Enable containerd service
  ansible.builtin.systemd:
      name: containerd
      enabled: true
      state: started
