---
- name: Check Argo CD deployments
  ansible.builtin.command:
      cmd: kubectl get deployments -n {{ argocd_namespace }}
  register: argocd_deployments
  changed_when: false

- name: Show Argo CD deployments
  ansible.builtin.debug:
      var: argocd_deployments.stdout_lines

- name: Check Argo CD server service
  ansible.builtin.command:
      cmd: kubectl get service argocd-server -n {{ argocd_namespace }}
  register: argocd_service
  changed_when: false

- name: Show Argo CD server service
  ansible.builtin.debug:
      var: argocd_service.stdout_lines
