---
github_runner_user: '{{ ansible_user }}'

github_runner_version: '2.329.0'

github_runner_repo: 'https://github.com/naman22a/online-judge-platform'

github_runner_name: '{{ inventory_hostname }}'

github_runner_labels:
    - self-hosted
    - linux
    - x64
    - think-server

github_runner_dir: '/home/{{ github_runner_user }}/actions-runner'

github_runner_url: >-
    https://github.com/actions/runner/releases/download/v{{ github_runner_version }}/actions-runner-linux-x64-{{ github_runner_version }}.tar.gz

github_runner_work_dir: '_work'
