---
- name: Restart k3s
  ansible.builtin.systemd:
      name: k3s
      state: restarted

- name: Add user to k3s group
  ansible.builtin.user:
      name: '{{ k3s_user }}'
      groups: k3s
      append: true
